export const colors = [
    {color: 'red'},
    {color: 'maroon'},
    {color: 'yellow'},
    {color: 'DarkGreen'},
    {color: 'lime'},
    {color: 'pink'},
    {color: 'Aqua'},
    {color: 'MediumVioletRed'},
    {color: 'Navy'},
    {color: 'LightSalmon'},
    {color: 'gold'},
    {color: 'OrangeRed'},
    {color: 'tomato'},
    {color: 'SteelBlue'},
    {color: 'CadetBlue'},
    {color: 'White'},
    {color: 'Gray'},
    {color: 'DarkOliveGreen'},
];
